name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: android/vision-quickstart/
      run: chmod +x gradlew
      
    - name: Build with Gradle
      working-directory: android/vision-quickstart/
      run: ./gradlew build
    
    - run:  ls -lsR
    
    - uses: actions/upload-artifact@v3
      with:
          name: ml-kit-vision-debug-apk
          path: android/vision-quickstart/app/build/outputs/apk/debug/app-debug.apk
